pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=PartTimeLegend
      - check-success=Powershell
      - check-success=Docker
    actions:
      merge:
        method: merge
