FROM linuxbrew/linuxbrew
RUN apt-get update
RUN apt-get upgrade
RUN apt-get dist-upgrade
HEALTHCHECK NONE
LABEL maintainer="hi@antonybailey.net"
RUN ["mkdir", "/setup"]
WORKDIR /setup
COPY NewMachineSetup.sh /setup
RUN /setup/./NewMachineSetup.sh