#!/usr/bin/env bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew update
packages=("git"
  "git-lfs"
  "meld"
  "ruby"
  "go"
  "python"
  "dotnet"
  "dotnet-sdk"
  "node"
  "visual-studio-code"
  "postman"
  "visual-studio"
  "010-editor"
  "electrum"
  "google-chrome"
  "firefox"
  "terraform"
  "packer"
  "tflint"
  "p7zip"
  "powershell"
  "cmake"
  "burp-suite"
  "autopsy"
  "balenaetcher"
  "yarn"
  "pgadmin4"
  "azure-data-studio"
  "nosql-workbench"
  "sqltoolbelt"
  "openssh"
  "openssl"
  "slack"
  "teamviewer"
  "curl"
  "wireshark"
  "nmap"
  "wireguard-go"
  "awscli"
  "azure-cli"
  "docker"
  "helm"
  "kubernetes-cli"
  "minikube"
  "zoom"
  "microsoft-teams"
  "k9s")

for package in ${packages[@]}; do
  brew install $package
  status=$?
  [ $status -eq 0 ] && echo "$package command was successfully" || echo "$package failed to install sucessfully"
done
