name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag parttimelegend/newmachinebuild:$(date +%s)
    - name: Docker image list
      run: docker images
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
      id: extract_branch  
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      if: steps.extract_branch.outputs.branch == 'master'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish to Docker Hub
      run: docker push parttimelegend/newmachinebuild
      if: steps.extract_branch.outputs.branch == 'master'
