name: Powershell

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run script
      run: .\BaseMachineSetup.ps1
      shell: powershell
